### ISSUE TITLE
Unreferenced local variable warning

### ISSUE THREAD

**Issue by petko** [ksherlock/lemon--#3]
I am trying out your fork of Lemon and I am impressed so far!

I've just stumbled upon something small, which I am not sure whether is caused by your fork or by the original lemon code (or by me doing something stupid).

When I compile even the simplest grammar in Visual C++ 2015, I get the following warning:
`Grammar.cpp(957): warning C4101: 'yylhsminor': unreferenced local variable`

It happens for this grammar for example:
```
input		::= expr(E). { std::cout << E; }
expr(A)		::= expr(E) PLUS VAL(V). { A = E + V; }
expr(A)		::= VAL(V). { A = V; }
```

Is it something that I am doing wrong or is it a quirk in the code?

**Comment by ksherlock** [comment]
Thanks for your comments! That warning is harmless - the generated code includes a temporary variable (`yylhsminor`) that isn't used.  The C-generated code uses that variable but it looks like the C++ generated code won't ever use it.  I'll confirm and eliminate it if possible.

**Comment by petko** [comment]
Excellent! Thank you very much for confirming it.

**Comment by ksherlock** [comment]
It has been fixed.
