### ISSUE TITLE
Stable commit

### ISSUE THREAD

**Issue by petko** [ksherlock/lemon--#6]
I see that there is no new release since late 2017. Is the last commit in master considered stable to use? I currently use commit from 2017-08-07 in my project.

**Comment by ksherlock** [comment]
Yes, the master branch should be stable.  There were some changes to upstream lemon last year that introduced some bugs, particularly involving the error recovery (not used in SQLite).  All the bugs I encountered have been fixed. If you find any problems, I'll look into them.

**Comment by petko** [comment]
Thank you. Looks good so far..
